repos:
  - repo: local
    hooks:
      - id: sigma-check
        name: sigma check
        language: system
        entry: sigma check --fail-on-error --fail-on-issues
        files: ^detections/sigma/.*\.ya?ml$
