# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local     # Sigma
    hooks:
    -   id: sigma-check
        name: sigma check
        language: system
        entry: sigma check --fail-on-error --fail-on-issues
        files: ^detections/sigma/.*\.ya?ml$