name: Sigma CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pySigma
        run: pip install sigma-cli
      - name: Install pySigma validator
        run: pip install pySigma-validators-sigmahq
      - name: Validate rules
        run: sigma check detections/sigma \
          --fail-on-warning \
          --fail-on-issues
